spring:
  application:
    name: customers-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    schema: classpath:schema-mysql.sql
    data: classpath:data-mysql.sql
