apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://#dbhost#:3306/#dbname#?useSSL=false&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: #dbusername#
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-server
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: #dbpassword#
  APPLICATIONINSIGHTS_CONNECTION_STRING: #appinsightsconnectionstring#
