apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #appname#
  name: #appname#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #appname#
  template:
    metadata:
      labels:
        app: #appname#
    spec:
      containers:
        - image: #image#
          name: #appname#
          env:
            - name: "APPLICATIONINSIGHTS_CONFIGURATION_CONTENT"
              value: >-
                {
                    "role": {   
                        "name": "#appname#"
                      }
                }
            - name: "APPLICATIONINSIGHTS_CONNECTION_STRING"
              valueFrom:
                secretKeyRef:
                  name: secrets-server
                  key: APPLICATIONINSIGHTS_CONNECTION_STRING
            - name: "SPRING_DATASOURCE_URL"
              valueFrom:
                configMapKeyRef:
                  name: config-server
                  key: SPRING_DATASOURCE_URL
            - name: "SPRING_DATASOURCE_USERNAME"
              valueFrom:
                configMapKeyRef:
                  name: config-server
                  key: SPRING_DATASOURCE_USERNAME
            - name: "SPRING_DATASOURCE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: secrets-server
                  key: SPRING_DATASOURCE_PASSWORD
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
          securityContext:
            privileged: false

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: #appname#
  name: #appname#
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: #appname#
  type: ClusterIP
